### ISSUE TITLE
Build Not Completing

### ISSUE THREAD

**Issue by codehtmai** [g3r4n/arcgispack#1]
How long is the `npx arcgispack` build supposed to take? I let it run overnight, and no dice. It's sitting on the "building the API" step. I'm on WSL Ubuntu, and have also tried it on a clean Docker Alpine container.

**Comment by g3r4n** [comment]
Hi, thank you for your feedback. It's taking 250s on my Windows machine.
Will give a try on a docker image and come back to you.

**Comment by codehtmai** [comment]
I did end up getting an error, on both machines:

`Error: No module factory available for dependency type: CommonJsRequireDependency
    at addDependency (/mnt/c/code/LanganProjectsNext/node_modules/arcgispack/node_modules/webpack/lib/Compilation.js:669:12)
    at iterationOfArrayCallback (/mnt/c/code/LanganProjectsNext/node_modules/arcgispack/node_modules/webpack/lib/Compilation.js:186:3)
    at addDependenciesBlock (/mnt/c/code/LanganProjectsNext/node_modules/arcgispack/node_modules/webpack/lib/Compilation.js:687:5)
    at Compilation.processModuleDependencies (/mnt/c/code/LanganProjectsNext/node_modules/arcgispack/node_modules/webpack/lib/Compilation.js:698:4)`

**Comment by g3r4n** [comment]
I've done more test and find out that adding the arcgispack in a existing project with babel config and webpack config the project is crashing because of node_modules link.
I think the best way to use arcgispack is to build your bundle outside of any project. 
I'll add more information about this process in the ReadMe

**Comment by codehtmai** [comment]
Ok, that seems reasonable. I'll try having our CI build that first and then add it to /public before the project build.
